// <auto-generated />
namespace EMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Added_ValidationsForUserProfile_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_ValidationsForUserProfile_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202106131456305_Added_ValidationsForUserProfile_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
