// <auto-generated />
namespace EMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addedPassword_column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedPassword_column));
        
        string IMigrationMetadata.Id
        {
            get { return "202106101033567_addedPassword_column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
