// <auto-generated />
namespace EMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class stringlength_for_Rolename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stringlength_for_Rolename));
        
        string IMigrationMetadata.Id
        {
            get { return "202106131616509_stringlength_for_Rolename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
