// <auto-generated />
namespace EMS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adding_payslip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_payslip));
        
        string IMigrationMetadata.Id
        {
            get { return "202106141109483_adding_payslip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
